apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: homelab
      auth:
        serviceAccountSecretRef:
          name: onepassword-token
          key: token