resources:
  requests:
    cpu: 200m
    memory: 384Mi
  limits:
    cpu: 2
    memory: 768Mi
affinity: &preferNonControlPlane
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist

certController:
  resources:
    requests:
      cpu: 20m
      memory: 192Mi
    limits:
      cpu: 200m
      memory: 384Mi
  affinity: *preferNonControlPlane

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 192Mi
  affinity: *preferNonControlPlane
