server:
  ingress:
    enabled: false # Ingress is managed via Traefik IngressRoute
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity: &preferNonControlPlane
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
  extraArgs:
    - --insecure # Disable TLS because we're using Ingress with TLS termination

applicationSet:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity: *preferNonControlPlane

controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  affinity: *preferNonControlPlane

repoServer:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity: *preferNonControlPlane

redis:
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  affinity: *preferNonControlPlane

# External authentication
dex:
  enabled: false

metrics:
  enabled: true
  serviceMonitor:
    enabled: true

notifications:
  enabled: true
  secret:
    create: true
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 100m
      memory: 256Mi
  affinity: *preferNonControlPlane

configs:
  cm:
    kustomize.buildOptions: "--enable-helm"
