replicaCount: 1

ingress:
  enabled: false

timeline:
  storage: sqlite
  retention: 168h
  maxSize: 1Gi

persistence:
  enabled: true
  storageClassName: longhorn
  accessMode: ReadWriteOnce
  size: 2Gi

rbac:
  helm: true
  secrets: true
  viewRBAC: true
  viewWebhooks: true
  podExec: true
  podLogs: true
  portForward: true
  traffic: true
  metrics: true
  additionalRules:
    - apiGroups:
        - ""
      resources:
        - nodes
      verbs:
        - get
        - list
        - watch
        - patch
    - apiGroups:
        - ""
      resources:
        - pods/eviction
      verbs:
        - create

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi
