[tools]
kubectl = "1.36"
terraform = "1.15"
helm = "3.21"
kustomize = "5.8"
task = "3.52"
jq = "1.8"
talosctl = "1.13"
cilium-cli = "0.19"

[env]
KUBECONFIG = "{{config_root}}/.kubeconfig/config"
TALOSCONFIG = "{{config_root}}/.talosconfig/config"
_.file = ".env"
