acl internal {
	192.168.0.0/24;
	localhost;
};

options {
  forwarders {
    1.1.1.1;
    1.0.0.1;
  };
  allow-query { internal; };
};

zone "home.home.lobotechworks.pt" IN {
  type master;
  file "/etc/bind/home-lobotechworks-pt.zone";
};