apiVersion: cilium.io/v2alpha1
kind: CiliumL2AnnouncementPolicy
metadata:
  name: ingress
spec:
  serviceSelector:
    matchLabels:
      homelab.lobotechworks.pt/load-balancer: ingress
  externalIPs: false
  loadBalancerIPs: true
