deployment:
  replicas: 2

podDisruptionBudget:
  enabled: true
  minAvailable: 1

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik

gateway:
  enabled: true
  name: internal
  namespace: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-cluster-issuer
  listeners:
    web: null
    websecure:
      port: 8443
      hostname: "*.home.lobotechworks.pt"
      protocol: HTTPS
      namespacePolicy:
        from: All
      certificateRefs:
        - name: internal-gateway-tls
          kind: Secret
          group: ""
      mode: Terminate

gatewayClass:
  enabled: true
  name: traefik

api:
  dashboard: true

ingressRoute:
  dashboard:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true
    ingressClass: traefik
    publishedService:
      enabled: true
  kubernetesGateway:
    enabled: true
    crossProviderNamespaces:
      - traefik
    statusAddress:
      service:
        enabled: true
        name: traefik
        namespace: traefik

ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    http:
      tls:
        enabled: true

service:
  type: LoadBalancer
  annotations:
    lbipam.cilium.io/ips: 192.168.1.200
  labels:
    homelab.lobotechworks.pt/load-balancer: main
  spec:
    externalTrafficPolicy: Cluster
    loadBalancerClass: io.cilium/l2-announcer

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - topologyKey: kubernetes.io/hostname
        labelSelector:
          matchLabels:
            app.kubernetes.io/name: traefik

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi
