namespaceOverride: "traefik"

service:
  type: LoadBalancer   # expose Traefik via LoadBalancer service
  ports:
    web:
      port: 80
      expose: true
    websecure:
      port: 443
      expose: true

additionalArguments:
  - "--api.insecure=true"  # enable Traefik dashboard (insecure for testing only)

ingressRoute:
  dashboard:
    enabled: true

replicas: 2

resources:
  requests:
    cpu: "100m"
    memory: "100Mi"
  limits:
    cpu: "500m"
    memory: "500Mi"
