apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-discord-credentials
  namespace: prometheus-stack
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-discord-credentials
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: discord/homelab_alerts_webhook
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
