prometheus:
  prometheusSpec:
    retention: 15d
    retentionSize: 20GiB
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
    scrapeInterval: 30s
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector:
      matchLabels: &prometheusInstance
        prometheus: kube-prometheus-stack
    ruleSelectorNilUsesHelmValues: false
    ruleSelector:
      matchLabels: *prometheusInstance
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector:
      matchLabels: *prometheusInstance
    probeSelectorNilUsesHelmValues: false
    probeSelector:
      matchLabels: *prometheusInstance
    scrapeConfigSelectorNilUsesHelmValues: false
    scrapeConfigSelector:
      matchLabels: *prometheusInstance

alertmanager:
  alertmanagerSpec:
    retention: 72h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

grafana:
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 5Gi
    accessModes:
      - ReadWriteOnce
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  ingress:
    enabled: false
  serviceMonitor:
    labels: *prometheusInstance

commonLabels: *prometheusInstance

kube-state-metrics:
  prometheus:
    monitor:
      additionalLabels: *prometheusInstance

prometheus-node-exporter:
  prometheus:
    monitor:
      additionalLabels: *prometheusInstance

