# Add leader election namespace to prevent RBAC permissions errors
global:
  leaderElection:
    namespace: cert-manager
crds:
  enabled: true
  keep: true

config:
  apiVersion: controller.config.cert-manager.io/v1alpha1
  kind: ControllerConfiguration
  enableGatewayAPI: true

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 200m
    memory: 128Mi
affinity: &preferNonControlPlane
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: DoesNotExist

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      cpu: 200m
      memory: 256Mi
  affinity: *preferNonControlPlane

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 192Mi
  affinity: *preferNonControlPlane
