apiVersion: v1
kind: Secret
metadata:
  name: proxmox-csi-plugin
  namespace: csi-proxmox
type: Opaque
stringData:
  config.yaml: |
    clusters:
      - url: https://192.168.0.100:8006/api2/json
        insecure: true
        token_id: "kubernetes-csi@pve!csi"
        token_secret: ""
        region: cluster-01