ingress:
  enabled: true
  className: traefik
  hosts:
    - host: uptime.home.lobotechworks.pt
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: uptime-kuma-tls
      hosts:
        - uptime.home.lobotechworks.pt

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi