defaultSettings:
  defaultDataPath: /data/longhorn
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: true
  nodeDownPodDeletionPolicy: "do-nothing"
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: true
  defaultLonghornStaticStorageClass: "longhorn"
  allowCollectingLonghornUsageMetrics: false
  storageMinimalAvailablePercentage: 10

defaultBackupStore:
  backupTarget: s3://backups-longhorn@us-east-1/
  backupTargetCredentialSecret: rustfs-credentials

ingress:
  enabled: false

preUpgradeChecker:
  jobEnabled: false
