defaultSettings:
  defaultDataPath: /var/mnt/longhorn
  defaultReplicaCount: 2
  replicaSoftAntiAffinity: true
  nodeDownPodDeletionPolicy: "do-nothing"
  allowRecurringJobWhileVolumeDetached: true
  createDefaultDiskLabeledNodes: false
  defaultLonghornStaticStorageClass: "longhorn"
  allowCollectingLonghornUsageMetrics: false
  storageMinimalAvailablePercentage: 10

defaultBackupStore:
  backupTarget: s3://backups-longhorn@us-east-1/
  backupTargetCredentialSecret: rustfs-credentials

ingress:
  enabled: true
  ingressClassName: traefik
  host: longhorn.home.lobotechworks.pt
  tls: true
  tlsSecret: longhorn-frontend-tls
  path: /
  pathType: Prefix
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
    traefik.ingress.kubernetes.io/router.tls: "true"

preUpgradeChecker:
  jobEnabled: false

metrics:
  serviceMonitor:
    enabled: true
    additionalLabels:
      prometheus: kube-prometheus-stack

longhornManager:
  resources:
    requests:
      cpu: 50m
      memory: 192Mi
    limits:
      cpu: 500m
      memory: 384Mi
