apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credentials
  namespace: n8n
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: n8n-credentials
    creationPolicy: Owner
  data:
    - secretKey: N8N_ENCRYPTION_KEY
      remoteRef:
        key: n8n/encryption_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: N8N_BASIC_AUTH_USER
      remoteRef:
        key: n8n/basic_auth_user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: N8N_BASIC_AUTH_PASSWORD
      remoteRef:
        key: n8n/basic_auth_password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
