timezone: "Europe/Lisbon"

# Recreate avoids the RWO rollout deadlock
strategy:
  type: Recreate

db:
  type: sqlite

existingEncryptionKeySecret: "n8n-credentials"

main:
  editorBaseUrl: "https://n8n.home.lobotechworks.pt"
  extraEnvVars:
    N8N_BASIC_AUTH_ACTIVE: "true"
  extraSecretNamesForEnvFrom:
    - n8n-credentials
  persistence:
    enabled: true
    storageClass: longhorn
    size: 5Gi
    accessMode: ReadWriteOnce
  resources:
    requests:
      memory: 384Mi
      cpu: 200m
    limits:
      memory: 1024Mi
      cpu: 1
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist

webhook:
  url: "https://n8n.home.lobotechworks.pt"
