apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-critical
  resources:
    requests:
      storage: 5Gi
